### ISSUE TITLE
LICENSE for this project

### ISSUE THREAD

**Issue by zabor2432** [dagster-io/project-dagster-university#27]
Hi, 

Is there any chance that there this project will have any license? I wanted to fork this repo and do some personal changes on public fork but it is not so legal right now.

Thanks

**Comment by cmpadden** [comment]
Hi @zabor2432 - thank you for the suggestion.

Apache License 2.0 has been added to be aligned with the primary `dagster-io/dagster` repository. I hope this helps!

**Comment by zabor2432** [comment]
Fabulous, thanks!
